# Generated by Django 3.2.20 on 2023-10-25 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value1', models.IntegerField()),
                ('value2', models.IntegerField()),
                ('value3', models.IntegerField()),
                ('value4', models.IntegerField()),
                ('value5', models.IntegerField()),
                ('value6', models.IntegerField()),
                ('value7', models.IntegerField()),
                ('value8', models.IntegerField()),
                ('value9', models.IntegerField()),
                ('value10', models.IntegerField()),
                ('value11', models.IntegerField()),
                ('value12', models.IntegerField()),
                ('value13', models.IntegerField()),
                ('value14', models.IntegerField()),
                ('value15', models.IntegerField()),
                ('value16', models.IntegerField()),
                ('vote_type', models.CharField(choices=[('vote01', 'Vote01'), ('vote02', 'Vote02')], max_length=10)),
                ('category', models.CharField(blank=True, max_length=10, null=True)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chart_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
