# Generated by Django 4.2.6 on 2023-10-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartdata',
            name='value1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chartdata',
            name='value10',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chartdata',
            name='value11',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chartdata',
            name='value12',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chartdata',
            name='value13',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chartdata',
            name='value14',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chartdata',
            name='value15',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chartdata',
            name='value16',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chartdata',
            name='value2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chartdata',
            name='value3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chartdata',
            name='value4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chartdata',
            name='value5',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chartdata',
            name='value6',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chartdata',
            name='value7',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chartdata',
            name='value8',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chartdata',
            name='value9',
            field=models.IntegerField(default=0),
        ),
    ]
