# Generated by Django 3.2.20 on 2023-10-25 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChartData',
        ),
        migrations.RemoveField(
            model_name='userquiz',
            name='question',
        ),
        migrations.RemoveField(
            model_name='userquiz',
            name='user',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='UserQuiz',
        ),
    ]
