# Generated by Django 3.2.20 on 2023-10-25 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(default='', max_length=255)),
                ('name', models.TextField(default='')),
                ('content', models.TextField(default='')),
                ('image', models.ImageField(blank=True, default='', upload_to='images')),
                ('sdgs1', models.TextField(default='')),
                ('sdgs2', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='SDGs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='')),
                ('slug', models.SlugField(blank=True, default='')),
                ('image', models.ImageField(blank=True, default='', upload_to='images')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='introduction.category')),
            ],
        ),
    ]
